// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDglqMuLneIKC6oZ6_2pR3We80CWaTDho',
    appId: '1:395008372046:web:ac3d8c616b62b7a7fbc21f',
    messagingSenderId: '395008372046',
    projectId: 'spotifyflutter-a96e9',
    authDomain: 'spotifyflutter-a96e9.firebaseapp.com',
    storageBucket: 'spotifyflutter-a96e9.appspot.com',
    measurementId: 'G-VFV660N6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPL3hBQ8Nm13j3j_xNCSA8Cu9QutJ1JQ',
    appId: '1:395008372046:android:cd9fb056f0079f50fbc21f',
    messagingSenderId: '395008372046',
    projectId: 'spotifyflutter-a96e9',
    storageBucket: 'spotifyflutter-a96e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC0fCEKkxMVjRLCVBhSSjqBpC8-OkQGD8',
    appId: '1:395008372046:ios:92b35b75726ffb03fbc21f',
    messagingSenderId: '395008372046',
    projectId: 'spotifyflutter-a96e9',
    storageBucket: 'spotifyflutter-a96e9.appspot.com',
    iosBundleId: 'com.example.spotifyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC0fCEKkxMVjRLCVBhSSjqBpC8-OkQGD8',
    appId: '1:395008372046:ios:92b35b75726ffb03fbc21f',
    messagingSenderId: '395008372046',
    projectId: 'spotifyflutter-a96e9',
    storageBucket: 'spotifyflutter-a96e9.appspot.com',
    iosBundleId: 'com.example.spotifyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDglqMuLneIKC6oZ6_2pR3We80CWaTDho',
    appId: '1:395008372046:web:76a79eca456afdfafbc21f',
    messagingSenderId: '395008372046',
    projectId: 'spotifyflutter-a96e9',
    authDomain: 'spotifyflutter-a96e9.firebaseapp.com',
    storageBucket: 'spotifyflutter-a96e9.appspot.com',
    measurementId: 'G-5ESB18S5WQ',
  );
}
